---

- name: "Gathering script deploy"
  copy:
    src: gathering.sh
    dest: /tmp/inode_check.sh
    mode: "0777"

- name: "Gathering script run"
  shell: /tmp/inode_check.sh > "/tmp/inode_check_{{ inventory_hostname }}.log"

- name: "dir create"
  file:
    path: "/tmp/inode_check/{{ inventory_hostname }}"
    state: directory
  delegate_to: localhost

- name: "Send file (Remote --> Local)"
  fetch:
    src: "/tmp/inode_check_{{ inventory_hostname }}.log"
    dest: "/tmp/inode_check/{{ inventory_hostname }}.log"
    flat: yes

- name: "Clean up - result File"
  file:
    path: "/tmp/inode_check_{{ inventory_hostname }}.log"
    state: absent

- name: "Clean up - script File"
  file:
    path: "/tmp/inode_check.sh"
    state: absent

- name: "Check script run"
  script: check.py
