---

- name: "Check script deploy"
  copy:
    src: check.sh
    dest: /tmp/inode_check.sh
    mode: "0777"

- name: "Script run"
  shell: /tmp/inode_check.sh > "inode_check_{{ inventory_hostname }}.log"

- name: "dir create"
  become: yes
  file:
    path: "/tmp/morpheus/node_check"
    state: directory
  delegate_to: localhost

- name: "Send file (Remote --> Local)"
  fetch:
    src: "/tmp/inode_check_{{ inventory_hostname }}.log"
    dest: "/tmp/morpheus/node_check/inode_check_{{ inventory_hostname }}.log"
